module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CART_COLLECTION:'cart',
    CATEGORY_COLLECTION:'category',
    ORDER_COLLECTION:'order',
    ADDRESS_COLLECTION:'address',
    WISHLIST_COLLECTION:'wishlist',
    COUPON_COLLECTION:"coupon",
    BANNER_COLLECTION:"banner"
}